// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFEy3WJlmAaJNk4-QhBoE-ayA-Ri4CUUw',
    appId: '1:74153425042:web:26af896a03640820404e4b',
    messagingSenderId: '74153425042',
    projectId: 'saferoute-11',
    authDomain: 'saferoute-11.firebaseapp.com',
    databaseURL: 'https://saferoute-11-default-rtdb.firebaseio.com',
    storageBucket: 'saferoute-11.firebasestorage.app',
    measurementId: 'G-QCG5HCSVXJ',
    androidClientId: '74153425042-ua7d62hg572jun7u1vmbfcpbjm37sape.apps.googleusercontent.com',
    iosClientId: '74153425042-g4k4g4f3jb8b1up8nd59m7v5talt6oir.apps.googleusercontent.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI07by9_dOumevc88ZBsIT_P1v3h47ia8',
    appId: '1:74153425042:android:26c76fc659f4c111404e4b',
    messagingSenderId: '74153425042',
    projectId: 'saferoute-11',
    databaseURL: 'https://saferoute-11-default-rtdb.firebaseio.com',
    storageBucket: 'saferoute-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk6Z9A9Pk-oDgeKRxR3Ortzy7brYDz6Ls',
    appId: '1:74153425042:ios:02eff83d8d10e056404e4b',
    messagingSenderId: '74153425042',
    projectId: 'saferoute-11',
    databaseURL: 'https://saferoute-11-default-rtdb.firebaseio.com',
    storageBucket: 'saferoute-11.firebasestorage.app',
    iosClientId: '74153425042-g4k4g4f3jb8b1up8nd59m7v5talt6oir.apps.googleusercontent.com',
    iosBundleId: 'com.example.saferoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk6Z9A9Pk-oDgeKRxR3Ortzy7brYDz6Ls',
    appId: '1:74153425042:ios:02eff83d8d10e056404e4b',
    messagingSenderId: '74153425042',
    projectId: 'saferoute-11',
    databaseURL: 'https://saferoute-11-default-rtdb.firebaseio.com',
    storageBucket: 'saferoute-11.firebasestorage.app',
    iosClientId: '74153425042-g4k4g4f3jb8b1up8nd59m7v5talt6oir.apps.googleusercontent.com',
    iosBundleId: 'com.example.saferoute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFEy3WJlmAaJNk4-QhBoE-ayA-Ri4CUUw',
    appId: '1:74153425042:web:76d4a29344571c65404e4b',
    messagingSenderId: '74153425042',
    projectId: 'saferoute-11',
    authDomain: 'saferoute-11.firebaseapp.com',
    databaseURL: 'https://saferoute-11-default-rtdb.firebaseio.com',
    storageBucket: 'saferoute-11.firebasestorage.app',
    measurementId: 'G-THQM5ZMRVK',
  );
}
